#
# GNUmakefile for target NSNumberStress_test
# begin - generated by buildtool
#

include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME= NSNumberStress_test

NSNumberStress_test_OBJC_FILES = NSNumberStress_test/main.m 

NSNumberStress_test_C_FILES = 

NSNumberStress_test_CPP_FILES = 

NSNumberStress_test_OBJCPP_FILES = 

NSNumberStress_test_HEADER_FILES = 

NSNumberStress_test_RESOURCE_FILES = 

ADDITIONAL_INCLUDE_DIRS += -I. \
	-I./NSNumberStress_test 

ADDITIONAL_OBJC_LIBS += 

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/common.make
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble

#
# end - generated makefile
#
